<?php

namespace Database\Seeders;

use App\Models\Branch;
use App\Models\Region;
use App\Models\ServiceArea;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceAreaSeeder extends Seeder
{
    public function run(): void
    {
        $regionMap = [
            'BALI NUSRA' => 'BALNUS',
            'JATIM' => 'JATIM',
            'JATENG DIY' => 'JATENGDIY',
        ];

        $data = [
            ['TOP', 'DHARMASABA UBUNG', 'DENPASAR', 'BALI NUSRA'],
            ['UBN', 'DHARMASABA UBUNG', 'DENPASAR', 'BALI NUSRA'],
            ['GIN', 'GIANYAR', 'DENPASAR', 'BALI NUSRA'],
            ['BLI', 'GIANYAR', 'DENPASAR', 'BALI NUSRA'],
            ['KNT', 'GIANYAR', 'DENPASAR', 'BALI NUSRA'],
            ['NGR', 'JEMBRANA', 'DENPASAR', 'BALI NUSRA'],
            ['GMK', 'JEMBRANA', 'DENPASAR', 'BALI NUSRA'],
            ['JBR', 'JIMBARAN', 'DENPASAR', 'BALI NUSRA'],
            ['KLM', 'KALIASEM', 'DENPASAR', 'BALI NUSRA'],
            ['NSD', 'KUTA', 'DENPASAR', 'BALI NUSRA'],
            ['KUT', 'KUTA', 'DENPASAR', 'BALI NUSRA'],
            ['MMN', 'MONANG MANING', 'DENPASAR', 'BALI NUSRA'],
            ['SMY', 'MONANG MANING', 'DENPASAR', 'BALI NUSRA'],
            ['BNO', 'SANUR', 'DENPASAR', 'BALI NUSRA'],
            ['SAU', 'SANUR', 'DENPASAR', 'BALI NUSRA'],
            ['APR', 'SEMARAPURA', 'DENPASAR', 'BALI NUSRA'],
            ['SMA', 'SEMARAPURA', 'DENPASAR', 'BALI NUSRA'],
            ['CDS', 'SEMARAPURA', 'DENPASAR', 'BALI NUSRA'],
            ['LVN', 'SINGARAJA', 'DENPASAR', 'BALI NUSRA'],
            ['SGR', 'SINGARAJA', 'DENPASAR', 'BALI NUSRA'],
            ['SRR', 'SINGARAJA', 'DENPASAR', 'BALI NUSRA'],
            ['PUA', 'SINGARAJA', 'DENPASAR', 'BALI NUSRA'],
            ['BTR', 'TABANAN', 'DENPASAR', 'BALI NUSRA'],
            ['TBN', 'TABANAN', 'DENPASAR', 'BALI NUSRA'],
            ['SWI', 'UBUD', 'DENPASAR', 'BALI NUSRA'],
            ['UBU', 'UBUD', 'DENPASAR', 'BALI NUSRA'],
            ['TPS', 'UBUD', 'DENPASAR', 'BALI NUSRA'],
            ['WWR', 'ENDE', 'FLORES', 'BALI NUSRA'],
            ['BJW', 'ENDE', 'FLORES', 'BALI NUSRA'],
            ['LBO', 'LABUAN BAJO', 'FLORES', 'BALI NUSRA'],
            ['RTE', 'LABUAN BAJO', 'FLORES', 'BALI NUSRA'],
            ['REO', 'LABUAN BAJO', 'FLORES', 'BALI NUSRA'],
            ['LWB', 'MAUMERE', 'FLORES', 'BALI NUSRA'],
            ['MMR', 'MAUMERE', 'FLORES', 'BALI NUSRA'],
            ['LRT', 'MAUMERE', 'FLORES', 'BALI NUSRA'],
            ['END', 'ENDE', 'FLORES', 'BALI NUSRA'],
            ['BWG', 'BANYUWANGI', 'JEMBER', 'JATIM'],
            ['KET', 'BANYUWANGI', 'JEMBER', 'JATIM'],
            ['WSO', 'BANYUWANGI', 'JEMBER', 'JATIM'],
            ['BOW', 'BONDOWOSO', 'JEMBER', 'JATIM'],
            ['PRJ', 'BONDOWOSO', 'JEMBER', 'JATIM'],
            ['SKS', 'BONDOWOSO', 'JEMBER', 'JATIM'],
            ['BCK', 'GENTENG', 'JEMBER', 'JATIM'],
            ['GEN', 'GENTENG', 'JEMBER', 'JATIM'],
            ['GLM', 'GENTENG', 'JEMBER', 'JATIM'],
            ['KBR', 'GENTENG', 'JEMBER', 'JATIM'],
            ['MCR', 'GENTENG', 'JEMBER', 'JATIM'],
            ['PSG', 'GENTENG', 'JEMBER', 'JATIM'],
            ['RGJ', 'GENTENG', 'JEMBER', 'JATIM'],
            ['AJS', 'JEMBER', 'JEMBER', 'JATIM'],
            ['JER', 'JEMBER', 'JEMBER', 'JATIM'],
            ['KLT', 'JEMBER', 'JEMBER', 'JATIM'],
            ['SKW', 'JEMBER', 'JEMBER', 'JATIM'],
            ['SPO', 'JEMBER', 'JEMBER', 'JATIM'],
            ['KBS', 'KEBONSARI', 'JEMBER', 'JATIM'],
            ['JTO', 'LUMAJANG', 'JEMBER', 'JATIM'],
            ['KKH', 'LUMAJANG', 'JEMBER', 'JATIM'],
            ['LMJ', 'LUMAJANG', 'JEMBER', 'JATIM'],
            ['PII', 'LUMAJANG', 'JEMBER', 'JATIM'],
            ['SDO', 'LUMAJANG', 'JEMBER', 'JATIM'],
            ['TPH', 'LUMAJANG', 'JEMBER', 'JATIM'],
            ['YSN', 'LUMAJANG', 'JEMBER', 'JATIM'],
            ['GND', 'PROBOLINGGO', 'JEMBER', 'JATIM'],
            ['KRZ', 'PROBOLINGGO', 'JEMBER', 'JATIM'],
            ['LCE', 'PROBOLINGGO', 'JEMBER', 'JATIM'],
            ['PBL', 'PROBOLINGGO', 'JEMBER', 'JATIM'],
            ['PTN', 'PROBOLINGGO', 'JEMBER', 'JATIM'],
            ['SKP', 'PROBOLINGGO', 'JEMBER', 'JATIM'],
            ['TGS', 'PROBOLINGGO', 'JEMBER', 'JATIM'],
            ['ABL', 'PUGER', 'JEMBER', 'JATIM'],
            ['BUG', 'PUGER', 'JEMBER', 'JATIM'],
            ['JGW', 'PUGER', 'JEMBER', 'JATIM'],
            ['KNO', 'PUGER', 'JEMBER', 'JATIM'],
            ['PUG', 'PUGER', 'JEMBER', 'JATIM'],
            ['RBP', 'PUGER', 'JEMBER', 'JATIM'],
            ['TGU', 'PUGER', 'JEMBER', 'JATIM'],
            ['ASB', 'SITUBONDO', 'JEMBER', 'JATIM'],
            ['BKI', 'SITUBONDO', 'JEMBER', 'JATIM'],
            ['MLD', 'SITUBONDO', 'JEMBER', 'JATIM'],
            ['SIT', 'SITUBONDO', 'JEMBER', 'JATIM'],
            ['KEF', 'ATAMBUA', 'KUPANG', 'BALI NUSRA'],
            ['ATB', 'ATAMBUA', 'KUPANG', 'BALI NUSRA'],
            ['BEN', 'ATAMBUA', 'KUPANG', 'BALI NUSRA'],
            ['KLH', 'MAUMERE', 'FLORES', 'BALI NUSRA'],
            ['SOE', 'ATAMBUA', 'KUPANG', 'BALI NUSRA'],
            ['NKN', 'ATAMBUA', 'KUPANG', 'BALI NUSRA'],
            ['OSP', 'KUPANG', 'KUPANG', 'BALI NUSRA'],
            ['KPN', 'KUPANG', 'KUPANG', 'BALI NUSRA'],
            ['TNA', 'KUPANG', 'KUPANG', 'BALI NUSRA'],
            ['WGP', 'SUMBA', 'KUPANG', 'BALI NUSRA'],
            ['BAA', 'SUMBA', 'KUPANG', 'BALI NUSRA'],
            ['WKB', 'SUMBA', 'KUPANG', 'BALI NUSRA'],
            ['SEB', 'SUMBA', 'KUPANG', 'BALI NUSRA'],
            ['BBE', 'BAMBE', 'LAMONGAN', 'JATIM'],
            ['BCR', 'BANCAR', 'LAMONGAN', 'JATIM'],
            ['JTR', 'BANCAR', 'LAMONGAN', 'JATIM'],
            ['KRK', 'BANCAR', 'LAMONGAN', 'JATIM'],
            ['MRR', 'BANCAR', 'LAMONGAN', 'JATIM'],
            ['BJN', 'BOJONEGORO', 'LAMONGAN', 'JATIM'],
            ['KDU', 'BOJONEGORO', 'LAMONGAN', 'JATIM'],
            ['PAD', 'BOJONEGORO', 'LAMONGAN', 'JATIM'],
            ['SMJ', 'BOJONEGORO', 'LAMONGAN', 'JATIM'],
            ['BPG', 'CERME', 'LAMONGAN', 'JATIM'],
            ['BWN', 'CERME', 'LAMONGAN', 'JATIM'],
            ['CRM', 'CERME', 'LAMONGAN', 'JATIM'],
            ['DDS', 'CERME', 'LAMONGAN', 'JATIM'],
            ['KDE', 'CERME', 'LAMONGAN', 'JATIM'],
            ['SDY', 'CERME', 'LAMONGAN', 'JATIM'],
            ['GSK', 'GRESIK', 'LAMONGAN', 'JATIM'],
            ['POG', 'GRESIK', 'LAMONGAN', 'JATIM'],
            ['BBA', 'LAMONGAN', 'LAMONGAN', 'JATIM'],
            ['BDG', 'LAMONGAN', 'LAMONGAN', 'JATIM'],
            ['LMG', 'LAMONGAN', 'LAMONGAN', 'JATIM'],
            ['SDD', 'LAMONGAN', 'LAMONGAN', 'JATIM'],
            ['RGL', 'TUBAN', 'LAMONGAN', 'JATIM'],
            ['TNZ', 'TUBAN', 'LAMONGAN', 'JATIM'],
            ['KDI', 'KEDIRI', 'MADIUN', 'JATIM'],
            ['MJT', 'KEDIRI', 'MADIUN', 'JATIM'],
            ['NDL', 'KEDIRI', 'MADIUN', 'JATIM'],
            ['SBI', 'KEDIRI', 'MADIUN', 'JATIM'],
            ['CRB', 'MADIUN', 'MADIUN', 'JATIM'],
            ['MNZ', 'MADIUN', 'MADIUN', 'JATIM'],
            ['MSP', 'MADIUN', 'MADIUN', 'JATIM'],
            ['UTR', 'MADIUN', 'MADIUN', 'JATIM'],
            ['GGR', 'MAGETAN', 'MADIUN', 'JATIM'],
            ['JGO', 'MAGETAN', 'MADIUN', 'JATIM'],
            ['KRJ', 'MAGETAN', 'MADIUN', 'JATIM'],
            ['MGT', 'MAGETAN', 'MADIUN', 'JATIM'],
            ['NWI', 'MAGETAN', 'MADIUN', 'JATIM'],
            ['SAR', 'MAGETAN', 'MADIUN', 'JATIM'],
            ['WKU', 'MAGETAN', 'MADIUN', 'JATIM'],
            ['GON', 'NGANJUK', 'MADIUN', 'JATIM'],
            ['KTS', 'NGANJUK', 'MADIUN', 'JATIM'],
            ['NJK', 'NGANJUK', 'MADIUN', 'JATIM'],
            ['PRB', 'NGANJUK', 'MADIUN', 'JATIM'],
            ['WRJ', 'NGANJUK', 'MADIUN', 'JATIM'],
            ['GUR', 'PARE', 'MADIUN', 'JATIM'],
            ['KAA', 'PARE', 'MADIUN', 'JATIM'],
            ['PAE', 'PARE', 'MADIUN', 'JATIM'],
            ['PPR', 'PARE', 'MADIUN', 'JATIM'],
            ['WAT', 'PARE', 'MADIUN', 'JATIM'],
            ['JEN', 'PONOROGO', 'MADIUN', 'JATIM'],
            ['LOG', 'PONOROGO', 'MADIUN', 'JATIM'],
            ['PLG', 'PONOROGO', 'MADIUN', 'JATIM'],
            ['PNG', 'PONOROGO', 'MADIUN', 'JATIM'],
            ['PNZ', 'PONOROGO', 'MADIUN', 'JATIM'],
            ['PON', 'PONOROGO', 'MADIUN', 'JATIM'],
            ['SAT', 'PONOROGO', 'MADIUN', 'JATIM'],
            ['SLH', 'PONOROGO', 'MADIUN', 'JATIM'],
            ['SMO', 'PONOROGO', 'MADIUN', 'JATIM'],
            ['DRN', 'TRENGGALEK', 'MADIUN', 'JATIM'],
            ['PRI', 'TRENGGALEK', 'MADIUN', 'JATIM'],
            ['TRE', 'TRENGGALEK', 'MADIUN', 'JATIM'],
            ['GOM', 'KEBUMEN', 'MAGELANG', 'JATENG DIY'],
            ['KAK', 'KEBUMEN', 'MAGELANG', 'JATENG DIY'],
            ['KBM', 'KEBUMEN', 'MAGELANG', 'JATENG DIY'],
            ['KTW', 'KEBUMEN', 'MAGELANG', 'JATENG DIY'],
            ['MGE', 'MAGELANG', 'MAGELANG', 'JATENG DIY'],
            ['MTY', 'MAGELANG', 'MAGELANG', 'JATENG DIY'],
            ['KTA', 'PURWOREJO', 'MAGELANG', 'JATENG DIY'],
            ['MNK', 'PURWOREJO', 'MAGELANG', 'JATENG DIY'],
            ['MUN', 'PURWOREJO', 'MAGELANG', 'JATENG DIY'],
            ['PWJ', 'PURWOREJO', 'MAGELANG', 'JATENG DIY'],
            ['SWT', 'PURWOREJO', 'MAGELANG', 'JATENG DIY'],
            ['PRN', 'TEMANGGUNG', 'MAGELANG', 'JATENG DIY'],
            ['TEM', 'TEMANGGUNG', 'MAGELANG', 'JATENG DIY'],
            ['BTU', 'BATU', 'MALANG', 'JATIM'],
            ['KPO', 'BATU', 'MALANG', 'JATIM'],
            ['NTG', 'BATU', 'MALANG', 'JATIM'],
            ['BLB', 'BLIMBING', 'MALANG', 'JATIM'],
            ['BLR', 'BLITAR', 'MALANG', 'JATIM'],
            ['BNU', 'BLITAR', 'MALANG', 'JATIM'],
            ['KBN', 'BLITAR', 'MALANG', 'JATIM'],
            ['LDY', 'BLITAR', 'MALANG', 'JATIM'],
            ['PAN', 'BLITAR', 'MALANG', 'JATIM'],
            ['SNT', 'BLITAR', 'MALANG', 'JATIM'],
            ['WGI', 'BLITAR', 'MALANG', 'JATIM'],
            ['DNO', 'KEPANJEN', 'MALANG', 'JATIM'],
            ['GDG', 'KEPANJEN', 'MALANG', 'JATIM'],
            ['GKW', 'KEPANJEN', 'MALANG', 'JATIM'],
            ['KEP', 'KEPANJEN', 'MALANG', 'JATIM'],
            ['PGK', 'KEPANJEN', 'MALANG', 'JATIM'],
            ['SBP', 'KEPANJEN', 'MALANG', 'JATIM'],
            ['KLJ', 'KLOJEN', 'MALANG', 'JATIM'],
            ['BRG', 'MALANG', 'MALANG', 'JATIM'],
            ['MLG', 'MALANG', 'MALANG', 'JATIM'],
            ['SWJ', 'MALANG', 'MALANG', 'JATIM'],
            ['LWG', 'SINGOSARI', 'MALANG', 'JATIM'],
            ['PKS', 'SINGOSARI', 'MALANG', 'JATIM'],
            ['SGS', 'SINGOSARI', 'MALANG', 'JATIM'],
            ['TMP', 'SINGOSARI', 'MALANG', 'JATIM'],
            ['CAT', 'TULUNGAGUNG', 'MALANG', 'JATIM'],
            ['KWR', 'TULUNGAGUNG', 'MALANG', 'JATIM'],
            ['NGU', 'TULUNGAGUNG', 'MALANG', 'JATIM'],
            ['TUL', 'TULUNGAGUNG', 'MALANG', 'JATIM'],
            ['APG', 'TUREN', 'MALANG', 'JATIM'],
            ['BNR', 'TUREN', 'MALANG', 'JATIM'],
            ['DPT', 'TUREN', 'MALANG', 'JATIM'],
            ['GDI', 'TUREN', 'MALANG', 'JATIM'],
            ['SBM', 'TUREN', 'MALANG', 'JATIM'],
            ['TUR', 'TUREN', 'MALANG', 'JATIM'],
            ['DMP', 'BIMA', 'MATARAM', 'BALI NUSRA'],
            ['SIL', 'BIMA', 'MATARAM', 'BALI NUSRA'],
            ['BIM', 'BIMA', 'MATARAM', 'BALI NUSRA'],
            ['KMP', 'BIMA', 'MATARAM', 'BALI NUSRA'],
            ['TET', 'BIMA', 'MATARAM', 'BALI NUSRA'],
            ['SAP', 'BIMA', 'MATARAM', 'BALI NUSRA'],
            ['MTR', 'MATARAM', 'MATARAM', 'BALI NUSRA'],
            ['SGG', 'MATARAM', 'MATARAM', 'BALI NUSRA'],
            ['MBG', 'SELONG', 'MATARAM', 'BALI NUSRA'],
            ['SEL', 'SELONG', 'MATARAM', 'BALI NUSRA'],
            ['SBW', 'SUMBAWA', 'MATARAM', 'BALI NUSRA'],
            ['MLK', 'SUMBAWA', 'MATARAM', 'BALI NUSRA'],
            ['TLW', 'SUMBAWA', 'MATARAM', 'BALI NUSRA'],
            ['ALA', 'SUMBAWA', 'MATARAM', 'BALI NUSRA'],
            ['EMP', 'SUMBAWA', 'MATARAM', 'BALI NUSRA'],
            ['PRY', 'SWETA', 'MATARAM', 'BALI NUSRA'],
            ['SWE', 'SWETA', 'MATARAM', 'BALI NUSRA'],
            ['GER', 'SWETA', 'MATARAM', 'BALI NUSRA'],
            ['BKA', 'BREBES', 'PEKALONGAN', 'JATENG DIY'],
            ['BMU', 'BREBES', 'PEKALONGAN', 'JATENG DIY'],
            ['BRB', 'BREBES', 'PEKALONGAN', 'JATENG DIY'],
            ['KTM', 'BREBES', 'PEKALONGAN', 'JATENG DIY'],
            ['TTL', 'BREBES', 'PEKALONGAN', 'JATENG DIY'],
            ['BDY', 'PEKALONGAN', 'PEKALONGAN', 'JATENG DIY'],
            ['BTG', 'PEKALONGAN', 'PEKALONGAN', 'JATENG DIY'],
            ['PKL', 'PEKALONGAN', 'PEKALONGAN', 'JATENG DIY'],
            ['SBA', 'PEKALONGAN', 'PEKALONGAN', 'JATENG DIY'],
            ['CMA', 'PEMALANG', 'PEKALONGAN', 'JATENG DIY'],
            ['KDW', 'PEMALANG', 'PEKALONGAN', 'JATENG DIY'],
            ['KJE', 'PEMALANG', 'PEKALONGAN', 'JATENG DIY'],
            ['PML', 'PEMALANG', 'PEKALONGAN', 'JATENG DIY'],
            ['RDD', 'PEMALANG', 'PEKALONGAN', 'JATENG DIY'],
            ['BBT', 'PURBALINGGA', 'PEKALONGAN', 'JATENG DIY'],
            ['PBG', 'PURBALINGGA', 'PEKALONGAN', 'JATENG DIY'],
            ['ADW', 'TEGAL', 'PEKALONGAN', 'JATENG DIY'],
            ['BLU', 'TEGAL', 'PEKALONGAN', 'JATENG DIY'],
            ['MGN', 'TEGAL', 'PEKALONGAN', 'JATENG DIY'],
            ['SLW', 'TEGAL', 'PEKALONGAN', 'JATENG DIY'],
            ['TEG', 'TEGAL', 'PEKALONGAN', 'JATENG DIY'],
            ['BJR', 'BANJARNEGARA', 'PURWOKERTO', 'JATENG DIY'],
            ['KLP', 'BANJARNEGARA', 'PURWOKERTO', 'JATENG DIY'],
            ['MAN', 'CILACAP', 'PURWOKERTO', 'JATENG DIY'],
            ['CLC', 'CILACAP', 'PURWOKERTO', 'JATENG DIY'],
            ['GML', 'CILACAP', 'PURWOKERTO', 'JATENG DIY'],
            ['SDJ', 'CILACAP', 'PURWOKERTO', 'JATENG DIY'],
            ['AJB', 'PURWOKERTO', 'PURWOKERTO', 'JATENG DIY'],
            ['CLO', 'PURWOKERTO', 'PURWOKERTO', 'JATENG DIY'],
            ['BRD', 'PURWOKERTO', 'PURWOKERTO', 'JATENG DIY'],
            ['PWT', 'PURWOKERTO', 'PURWOKERTO', 'JATENG DIY'],
            ['KRY', 'SUKARAJA', 'PURWOKERTO', 'JATENG DIY'],
            ['MAO', 'SUKARAJA', 'PURWOKERTO', 'JATENG DIY'],
            ['BYM', 'SUKARAJA', 'PURWOKERTO', 'JATENG DIY'],
            ['SUK', 'SUKARAJA', 'PURWOKERTO', 'JATENG DIY'],
            ['WOS', 'WONOSOBO', 'PURWOKERTO', 'JATENG DIY'],
            ['BMK', 'BANYUMANIK', 'SEMARANG', 'JATENG DIY'],
            ['SMC', 'BANYUMANIK', 'SEMARANG', 'JATENG DIY'],
            ['SSL', 'BANYUMANIK', 'SEMARANG', 'JATENG DIY'],
            ['BOJ', 'BOJA', 'SEMARANG', 'JATENG DIY'],
            ['MJE', 'BOJA', 'SEMARANG', 'JATENG DIY'],
            ['MKG', 'BOJA', 'SEMARANG', 'JATENG DIY'],
            ['BAN', 'JEPARA', 'SEMARANG', 'JATENG DIY'],
            ['JPR', 'JEPARA', 'SEMARANG', 'JATENG DIY'],
            ['KEL', 'JEPARA', 'SEMARANG', 'JATENG DIY'],
            ['KMJ', 'JEPARA', 'SEMARANG', 'JATENG DIY'],
            ['PEC', 'JEPARA', 'SEMARANG', 'JATENG DIY'],
            ['GNK', 'JOHAR', 'SEMARANG', 'JATENG DIY'],
            ['JHR', 'JOHAR', 'SEMARANG', 'JATENG DIY'],
            ['KDL', 'KENDAL', 'SEMARANG', 'JATENG DIY'],
            ['SKR', 'KENDAL', 'SEMARANG', 'JATENG DIY'],
            ['WLR', 'KENDAL', 'SEMARANG', 'JATENG DIY'],
            ['DMA', 'KUDUS', 'SEMARANG', 'JATENG DIY'],
            ['KUD', 'KUDUS', 'SEMARANG', 'JATENG DIY'],
            ['MJP', 'MAJAPAHIT', 'SEMARANG', 'JATENG DIY'],
            ['JWN', 'PATI', 'SEMARANG', 'JATENG DIY'],
            ['PAT', 'PATI', 'SEMARANG', 'JATENG DIY'],
            ['TAY', 'PATI', 'SEMARANG', 'JATENG DIY'],
            ['LSE', 'REMBANG', 'SEMARANG', 'JATENG DIY'],
            ['RBN', 'REMBANG', 'SEMARANG', 'JATENG DIY'],
            ['SLI', 'SALATIGA', 'SEMARANG', 'JATENG DIY'],
            ['SUH', 'SALATIGA', 'SEMARANG', 'JATENG DIY'],
            ['SMT', 'TUGU', 'SEMARANG', 'JATENG DIY'],
            ['ABR', 'UNGARAN', 'SEMARANG', 'JATENG DIY'],
            ['BDN', 'UNGARAN', 'SEMARANG', 'JATENG DIY'],
            ['BWE', 'UNGARAN', 'SEMARANG', 'JATENG DIY'],
            ['UNR', 'UNGARAN', 'SEMARANG', 'JATENG DIY'],
            ['WNJ', 'UNGARAN', 'SEMARANG', 'JATENG DIY'],
            ['GDA', 'GEDANGAN', 'SIDOARJO', 'JATIM'],
            ['JOM', 'JOMBANG', 'SIDOARJO', 'JATIM'],
            ['MOJ', 'JOMBANG', 'SIDOARJO', 'JATIM'],
            ['NRJ', 'JOMBANG', 'SIDOARJO', 'JATIM'],
            ['POS', 'JOMBANG', 'SIDOARJO', 'JATIM'],
            ['DLA', 'MOJOKERTO', 'SIDOARJO', 'JATIM'],
            ['MIP', 'MOJOKERTO', 'SIDOARJO', 'JATIM'],
            ['MJS', 'MOJOKERTO', 'SIDOARJO', 'JATIM'],
            ['MRT', 'MOJOKERTO', 'SIDOARJO', 'JATIM'],
            ['NGI', 'MOJOKERTO', 'SIDOARJO', 'JATIM'],
            ['PCT', 'MOJOKERTO', 'SIDOARJO', 'JATIM'],
            ['BEJ', 'PANDAAN', 'SIDOARJO', 'JATIM'],
            ['GEM', 'PANDAAN', 'SIDOARJO', 'JATIM'],
            ['PDA', 'PANDAAN', 'SIDOARJO', 'JATIM'],
            ['PGE', 'PANDAAN', 'SIDOARJO', 'JATIM'],
            ['PWS', 'PANDAAN', 'SIDOARJO', 'JATIM'],
            ['BNL', 'PASURUAN', 'SIDOARJO', 'JATIM'],
            ['GDW', 'PASURUAN', 'SIDOARJO', 'JATIM'],
            ['GRA', 'PASURUAN', 'SIDOARJO', 'JATIM'],
            ['NJA', 'PASURUAN', 'SIDOARJO', 'JATIM'],
            ['PSN', 'PASURUAN', 'SIDOARJO', 'JATIM'],
            ['TOS', 'PASURUAN', 'SIDOARJO', 'JATIM'],
            ['SPJ', 'SEPANJANG', 'SIDOARJO', 'JATIM'],
            ['SDA', 'SIDOARJO', 'SIDOARJO', 'JATIM'],
            ['KRN', 'SUKODONO', 'SIDOARJO', 'JATIM'],
            ['SDN', 'SUKODONO', 'SIDOARJO', 'JATIM'],
            ['TUN', 'SUKODONO', 'SIDOARJO', 'JATIM'],
            ['TPO', 'TROPODO', 'SIDOARJO', 'JATIM'],
            ['WRU', 'WARU', 'SIDOARJO', 'JATIM'],
            ['DMO', 'DARMO', 'SURABAYA', 'JATIM'],
            ['GBG', 'GUBENG', 'SURABAYA', 'JATIM'],
            ['IJK', 'INJOKO', 'SURABAYA', 'JATIM'],
            ['JGR', 'JAGIR', 'SURABAYA', 'JATIM'],
            ['MYR', 'MANYAR', 'SURABAYA', 'JATIM'],
            ['RKT', 'RUNGKUT', 'SURABAYA', 'JATIM'],
            ['KPS', 'KAPASAN', 'SURABAYA', 'JATIM'],
            ['KBL', 'KEBALEN', 'SURABAYA', 'JATIM'],
            ['PRK', 'KEBALEN', 'SURABAYA', 'JATIM'],
            ['KJR', 'KENJERAN', 'SURABAYA', 'JATIM'],
            ['MGO', 'MERGOYOSO', 'SURABAYA', 'JATIM'],
            ['KLN', 'KALIANAK', 'SURABAYA', 'JATIM'],
            ['TNS', 'TANDES', 'SURABAYA', 'JATIM'],
            ['KNN', 'KANDANGAN', 'SURABAYA', 'JATIM'],
            ['LKI', 'LAKARSANTRI', 'SURABAYA', 'JATIM'],
            ['KRP', 'KARANGPILANG', 'SURABAYA', 'JATIM'],
            ['BKL', 'BANGKALAN', 'SURABAYA', 'JATIM'],
            ['KML', 'BANGKALAN', 'SURABAYA', 'JATIM'],
            ['ARB', 'BANGKALAN', 'SURABAYA', 'JATIM'],
            ['TBU', 'BANGKALAN', 'SURABAYA', 'JATIM'],
            ['BEA', 'BANGKALAN', 'SURABAYA', 'JATIM'],
            ['SPG', 'SAMPANG', 'SURABAYA', 'JATIM'],
            ['KPP', 'SAMPANG', 'SURABAYA', 'JATIM'],
            ['OMB', 'SAMPANG', 'SURABAYA', 'JATIM'],
            ['PME', 'PAMEKASAN', 'SURABAYA', 'JATIM'],
            ['WRP', 'PAMEKASAN', 'SURABAYA', 'JATIM'],
            ['PRG', 'SUMENEP', 'SURABAYA', 'JATIM'],
            ['SMP', 'SUMENEP', 'SURABAYA', 'JATIM'],
            ['BAB', 'SUMENEP', 'SURABAYA', 'JATIM'],
            ['ABU', 'SUMENEP', 'SURABAYA', 'JATIM'],
            ['SPD', 'SUMENEP', 'SURABAYA', 'JATIM'],
            ['AJA', 'SUMENEP', 'SURABAYA', 'JATIM'],
            ['SPK', 'SUMENEP', 'SURABAYA', 'JATIM'],
            ['MSL', 'SUMENEP', 'SURABAYA', 'JATIM'],
            ['ABT', 'SUMENEP', 'SURABAYA', 'JATIM'],
            ['BLO', 'BLORA', 'SURAKARTA', 'JATENG DIY'],
            ['CEP', 'BLORA', 'SURAKARTA', 'JATENG DIY'],
            ['NGA', 'BLORA', 'SURAKARTA', 'JATENG DIY'],
            ['RDB', 'BLORA', 'SURAKARTA', 'JATENG DIY'],
            ['BYL', 'BOYOLALI', 'SURAKARTA', 'JATENG DIY'],
            ['KTO', 'BOYOLALI', 'SURAKARTA', 'JATENG DIY'],
            ['GLD', 'GLADAG', 'SURAKARTA', 'JATENG DIY'],
            ['SLO', 'GLADAG', 'SURAKARTA', 'JATENG DIY'],
            ['KAR', 'KARANGANYAR', 'SURAKARTA', 'JATENG DIY'],
            ['TWM', 'KARANGANYAR', 'SURAKARTA', 'JATENG DIY'],
            ['KRT', 'KERTEN', 'SURAKARTA', 'JATENG DIY'],
            ['DLG', 'KLATEN', 'SURAKARTA', 'JATENG DIY'],
            ['KLX', 'KLATEN', 'SURAKARTA', 'JATENG DIY'],
            ['PEN', 'KLATEN', 'SURAKARTA', 'JATENG DIY'],
            ['BKG', 'PALUR', 'SURAKARTA', 'JATENG DIY'],
            ['MSO', 'PALUR', 'SURAKARTA', 'JATENG DIY'],
            ['SOP', 'PALUR', 'SURAKARTA', 'JATENG DIY'],
            ['GBU', 'PURWODADI', 'SURAKARTA', 'JATENG DIY'],
            ['GDO', 'PURWODADI', 'SURAKARTA', 'JATENG DIY'],
            ['PWB', 'PURWODADI', 'SURAKARTA', 'JATENG DIY'],
            ['TRO', 'PURWODADI', 'SURAKARTA', 'JATENG DIY'],
            ['WRO', 'PURWODADI', 'SURAKARTA', 'JATENG DIY'],
            ['SRG', 'SRAGEN', 'SURAKARTA', 'JATENG DIY'],
            ['BRN', 'WONOGIRI', 'SURAKARTA', 'JATENG DIY'],
            ['JSO', 'WONOGIRI', 'SURAKARTA', 'JATENG DIY'],
            ['SKH', 'WONOGIRI', 'SURAKARTA', 'JATENG DIY'],
            ['TWS', 'WONOGIRI', 'SURAKARTA', 'JATENG DIY'],
            ['WNG', 'WONOGIRI', 'SURAKARTA', 'JATENG DIY'],
            ['PWO', 'WONOGIRI', 'SURAKARTA', 'JATENG DIY'],
            ['BTL', 'BANTUL', 'YOGYAKARTA', 'JATENG DIY'],
            ['WTS', 'BANTUL', 'YOGYAKARTA', 'JATENG DIY'],
            ['KEN', 'KENTUNGAN', 'YOGYAKARTA', 'JATENG DIY'],
            ['BBS', 'KENTUNGAN', 'YOGYAKARTA', 'JATENG DIY'],
            ['KBU', 'KOTABARU', 'YOGYAKARTA', 'JATENG DIY'],
            ['WNS', 'KOTAGEDE', 'YOGYAKARTA', 'JATENG DIY'],
            ['KGD', 'KOTAGEDE', 'YOGYAKARTA', 'JATENG DIY'],
            ['BPN', 'KOTAGEDE', 'YOGYAKARTA', 'JATENG DIY'],
            ['PKM', 'PAKEM', 'YOGYAKARTA', 'JATENG DIY'],
            ['KLS', 'PAKEM', 'YOGYAKARTA', 'JATENG DIY'],
            ['SMN', 'SLEMAN', 'YOGYAKARTA', 'JATENG DIY'],
            ['GOD', 'SLEMAN', 'YOGYAKARTA', 'JATENG DIY'],
            ['PGR', 'PUGERAN', 'YOGYAKARTA', 'JATENG DIY'],
        ];

        DB::transaction(function () use ($data, $regionMap) {
            foreach ($data as [$workzone, $serviceArea, $branchName, $regionName]) {
                $regionCode = $regionMap[$regionName] ?? strtoupper(str_replace(' ', '', $regionName));
                $region = Region::firstOrCreate(
                    ['code' => $regionCode],
                    ['name' => $regionName === 'BALI NUSRA' ? 'REGION BALNUS' : ($regionName === 'JATIM' ? 'REGION JATIM' : 'REGION JATENG DIY'), 'is_active' => true]
                );
                // fallback: jika region name tidak sesuai, cari by name
                if (! $region->exists) {
                    $region = Region::where('name', 'REGION '.$regionName)->orWhere('name', $regionName)->first();
                    if (! $region) {
                        $region = Region::create(['code' => $regionCode, 'name' => 'REGION '.$regionName, 'is_active' => true]);
                    }
                }

                $branch = Branch::where('name', $branchName)->first();
                if (! $branch) {
                    $branch = Branch::create([
                        'code' => $branchName,
                        'name' => $branchName,
                        'region' => $region->name,
                        'region_id' => $region->id_region,
                        'is_active' => true,
                    ]);
                } else {
                    // pastikan region_id branch terisi
                    if (! $branch->region_id) {
                        $branch->update(['region_id' => $region->id_region, 'region' => $region->name]);
                    }
                }

                ServiceArea::updateOrCreate(
                    ['workzone' => $workzone],
                    [
                        'name' => $serviceArea,
                        'branch_id' => $branch->id_branch,
                        'region_id' => $region->id_region,
                        'is_active' => true,
                    ]
                );
            }
        });

        $this->command->info('ServiceAreas seeded: '.ServiceArea::count().' rows');
    }
}
